# Generated by Django 2.0.4 on 2018-11-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
