# Generated by Django 2.1.3 on 2019-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
