# Generated by Django 2.1.3 on 2018-11-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotelregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HotelRegister')),
            ],
            options={
                'db_table': 'hotelbooking',
            },
        ),
    ]
