# Generated by Django 2.1.3 on 2018-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelregister',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
