# Generated by Django 2.1.3 on 2018-11-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181117_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_out',
            field=models.DateField(blank=True),
        ),
    ]
