# Generated by Django 2.1.3 on 2018-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181119_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.CharField(choices=[('deluxe', 'DELUXE'), ('luxury', 'LUXURY')], default='deluxe', max_length=10),
        ),
    ]
