# Generated by Django 2.1.3 on 2018-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181127_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
