# Generated by Django 2.1.3 on 2018-11-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181127_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='bookingid',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='app.BookingInformation'),
        ),
    ]
