# Generated by Django 2.1.3 on 2018-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_roombooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='bookingid',
            field=models.CharField(max_length=100),
        ),
    ]
