# Generated by Django 2.1.3 on 2018-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181127_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
