# Generated by Django 2.1.3 on 2018-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181127_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConfirmation',
            fields=[
                ('checkin', models.CharField(blank=True, max_length=20)),
                ('checkout', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=20)),
                ('bookingid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roombook',
            },
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
