# Generated by Django 2.1.3 on 2018-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconfirmation',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
