# Generated by Django 2.1.3 on 2018-11-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181128_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconfirmation',
            name='hotel_name',
            field=models.CharField(max_length=50),
        ),
    ]
