# Generated by Django 2.1.3 on 2018-11-28 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181128_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconfirmation',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='bookingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BookingInformation'),
        ),
    ]
