# Generated by Django 2.1.3 on 2018-11-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181128_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomconfirmation',
            name='id',
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='bookingid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.BookingInformation'),
        ),
    ]
