# Generated by Django 2.1.3 on 2018-11-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181128_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomconfirmation',
            old_name='bookingid',
            new_name='booking_id',
        ),
    ]
