# Generated by Django 2.1.3 on 2018-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181128_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconfirmation',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
