# Generated by Django 2.1.3 on 2018-11-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20181128_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='booking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='booking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
