# Generated by Django 2.1.3 on 2018-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181128_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='booking_id',
            field=models.CharField(default='NULL', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkin',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkout',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='hotel_name',
            field=models.CharField(max_length=10),
        ),
    ]
