# Generated by Django 2.1.3 on 2018-11-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20181128_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconfirmation',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkout',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='hotel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='room',
            field=models.CharField(default='deluxe', max_length=10),
        ),
    ]
