# Generated by Django 2.1.3 on 2018-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20181128_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkin',
            field=models.DateTimeField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='roomconfirmation',
            name='checkout',
            field=models.DateTimeField(blank=True, max_length=100),
        ),
    ]
