# Generated by Django 2.1.3 on 2018-11-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20181128_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomConfirmation',
        ),
    ]
