# Generated by Django 2.1.3 on 2018-11-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_roomconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(blank=True)),
                ('checkout', models.DateField(blank=True)),
                ('email', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=10)),
                ('room', models.CharField(choices=[('deluxe', 'DELUXE'), ('luxury', 'LUXURY')], default='deluxe', max_length=10)),
            ],
            options={
                'db_table': 'roombooking',
            },
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='no_of_rooms',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='requirements',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
